apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kai-resource-isolator.fullname" . }}-ldpreload
  namespace: {{ include "kai-resource-isolator.namespace" . }}
  labels:
    {{- include "kai-resource-isolator.labels" . | nindent 4 }}
data:
  ld.so.preload: |
    {{ .Values.paths.containerVgpuMount }}/libvgpu.so
