apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kai-resource-isolator.webhook.fullname" . }}
  namespace: {{ include "kai-resource-isolator.namespace" . }}
  labels:
    {{- include "kai-resource-isolator.labels" . | nindent 4 }}
{{- if and .Values.tls.patch.enabled (not .Values.tls.certManager.enabled) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kai-resource-isolator.fullname" . }}-admission
  namespace: {{ include "kai-resource-isolator.namespace" . }}
  labels:
    {{- include "kai-resource-isolator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
